### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ZZZZZZZZeng** [hw-du/CBiT#1]
There is no ‘args.slide_window_step’ attribution in this ‘options.py’ file

-------------erro code：-----------------
发生异常: AttributeError
'Namespace' object has no attribute 'slide_window_step'
  File "/home/liuhao/zkx/CBiT-master/dataloaders/bert.py", line 32, in __init__
    self.train_slidewindow, self.train_slidewindow_by_user, self.user_count_slidewindow = self.get_train_dataset_slidewindow(args.slide_window_step)
  File "/home/liuhao/zkx/CBiT-master/main.py", line 16, in train
    train_loader, val_loader, test_loader = BertDataloader(args, dataset).get_pytorch_dataloaders()
  File "/home/liuhao/zkx/CBiT-master/main.py", line 28, in <module>
    train()

**Comment by hw-du** [comment]
You may find this hyperparameter at the last line of templates.py:
``
args.slide_window_step = 10 if 'ml' in args.dataset_code else 1
``

**Comment by ZZZZZZZZeng** [comment]
Thank you for your answer. I found that there was a problem in my Settings, which has been solved now.

**Comment by ZZZZZZZZeng** [comment]
> You may find this hyperparameter at the last line of templates.py: `args.slide_window_step = 10 if 'ml' in args.dataset_code else 1`

Thank you for your answer. I found that there was a problem in my Settings, which has been solved now.
